/* GENERATED by `npm run tokens:build` — do not edit. Source: source/ */

/**
 * Semantic colours of one theme. Core keys serve any product; the finance keys are this product's
 * vocabulary. Values are widened to string on purpose: a theme is a set of keys, not of literals.
 */
export type Palette = Record<keyof typeof lightPalette, string>;

export const lightPalette = {
  "bg": "#faf9f7",
  "bgPage": "#f3f1ed",
  "surface": "#ffffff",
  "surfaceRaised": "#f0ede8",
  "surfaceMuted": "#fcfbf9",
  "border": "#e6e2dc",
  "borderSoft": "#f0ede8",
  "text": "#1e1c19",
  "textSecondary": "#55504a",
  "textTertiary": "#6f685f",
  "textDisabled": "#a8a199",
  "accent": "#2f6b4f",
  "accentHover": "#21503b",
  "accentSoft": "#eaf2ed",
  "accentBorder": "#d6e6dc",
  "accentTint": "#f4f8f5",
  "onAccent": "#ffffff",
  "scrim": "rgba(20, 19, 17, 0.45)",
  "focus": "#2f6b4f",
  "paid": "#2f6b4f",
  "paidSoft": "#eaf2ed",
  "pending": "#8f877c",
  "dueSoon": "#8a6520",
  "dueSoonMark": "#b07e22",
  "dueSoonSoft": "#fdf6e9",
  "overdue": "#b4462a",
  "overdueSoft": "#fbede8",
  "overdueBorder": "#ebc9bc",
  "onOverdue": "#ffffff",
  "skipped": "#948c81",
  "skippedSoft": "#f0ede8"
} as const;

export const darkPalette: Palette = {
  "bg": "#141311",
  "bgPage": "#0f0e0d",
  "surface": "#1c1a17",
  "surfaceRaised": "#262320",
  "surfaceMuted": "#191714",
  "border": "#332f2a",
  "borderSoft": "#262320",
  "text": "#ece8e1",
  "textSecondary": "#b5aea4",
  "textTertiary": "#8f887e",
  "textDisabled": "#6b655c",
  "accent": "#6fb08f",
  "accentHover": "#86c2a3",
  "accentSoft": "#1e2b24",
  "accentBorder": "#2e4a3b",
  "accentTint": "#1a231e",
  "onAccent": "#141311",
  "scrim": "rgba(0, 0, 0, 0.6)",
  "focus": "#6fb08f",
  "paid": "#6fb08f",
  "paidSoft": "#1e2b24",
  "pending": "#8f887e",
  "dueSoon": "#d9a24a",
  "dueSoonMark": "#d9a24a",
  "dueSoonSoft": "#2a2416",
  "overdue": "#e07b5c",
  "overdueSoft": "#2e1e19",
  "overdueBorder": "#4a2c23",
  "onOverdue": "#141311",
  "skipped": "#6b655c",
  "skippedSoft": "#262320"
};

/**
 * CSS shadow recipes. Native must not use these raw: iOS takes shadowColor/Offset/Opacity/Radius
 * and Android takes elevation. Share the name, not the recipe.
 */
export const webShadows = {
  "overlay": {
    "light": "0 12px 32px rgba(30, 28, 25, 0.16)",
    "dark": "0 12px 32px rgba(0, 0, 0, 0.5)"
  }
} as const;

/** Closed type scale (D-09). Numbers: points on native, pixels on the web. */
export const text = {
  "xs": 11,
  "sm": 12,
  "md": 13,
  "base": 14,
  "lg": 16,
  "xl": 20,
  "2xl": 26
} as const;

export const space = {
  "1": 4,
  "2": 8,
  "3": 12,
  "4": 16,
  "5": 24,
  "6": 32,
  "7": 48,
  "8": 64
} as const;

export const radius = {
  "sm": 6,
  "md": 10,
  "lg": 13,
  "pill": 999
} as const;

export const motion = {
  "fast": 150,
  "base": 220
} as const;

/** Minimum touch target, in points. */
export const tap = 44;

/** Web chrome measurements. A native app sizes its own. */
export const layout = {
  "sidebarWidth": 232,
  "contentMax": 920,
  "bottomNavHeight": 60
} as const;

/**
 * CSS font stacks. Native does not use these: a device needs the family name of an installed or
 * bundled font, not a fallback list. Native families live in `tokens/core/fonts.ts`.
 */
export const fontStacks = {
  "ui": "'Libre Franklin', system-ui, -apple-system, 'Segoe UI', sans-serif",
  "mono": "'IBM Plex Mono', ui-monospace, 'SF Mono', Menlo, monospace"
} as const;
