/**
 * Builds the token artifacts from the DTCG source. Runs only here; the apps consume the output.
 *
 * Three artifacts, three unit policies:
 *   dist/tokens/tokens.css  CSS custom properties, values verbatim ("11px", "150ms")
 *   dist/tokens/index.ts    TypeScript constants, dimensions and durations as numbers
 *   (native reads the same index.ts; font families are NOT derived from the CSS stack)
 *
 * Names are preserved exactly as the web ships them today, so the first migration is a
 * value-for-value swap with no renaming. The `finance` group exists in the source to keep the
 * domain vocabulary visible; it is flattened on output until the apps are ready to rename.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import StyleDictionary from 'style-dictionary';

// Generated source, not build output: tsup compiles this into dist/.
const OUT = 'src';
const HEADER = '/* GENERATED by `npm run tokens:build` — do not edit. Source: source/ */\n';

/** Drops the `finance` group marker so `color.finance.paid` stays `--ds-color-paid`. */
const cssName = (token) => `--ds-${token.path.filter((p) => p !== 'finance').join('-')}`;

/** `11px` → 11, `150ms` → 150. Anything not purely numeric is returned untouched. */
const toNumber = (value) => {
  const match = /^(-?\d*\.?\d+)(px|ms)$/.exec(String(value).trim());
  return match ? Number(match[1]) : value;
};

/**
 * React Native does not parse the modern `rgb(r g b / a)` syntax, so colours reach the TypeScript
 * artifact as `rgba(r, g, b, a)` — still valid CSS, and the only form both platforms accept.
 */
const toRgba = (value) => {
  const match = /^rgb\(\s*(\d+)\s+(\d+)\s+(\d+)\s*\/\s*([\d.]+)\s*\)$/.exec(String(value).trim());
  return match ? `rgba(${match[1]}, ${match[2]}, ${match[3]}, ${match[4]})` : value;
};

const camel = (parts) => parts.map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1))).join('');
/** `color.text-secondary` → `textSecondary`, `bottom-nav.height` → `bottomNavHeight`. */
const leafName = (path) => camel(path.filter((p) => p !== 'finance').flatMap((p) => p.split('-')));

StyleDictionary.registerFormat({
  name: 'ds/css-vars',
  format: ({ dictionary, options }) => {
    const lines = dictionary.allTokens.map((t) => `  ${cssName(t)}: ${t.$value ?? t.value};`);
    const scheme = options.colorScheme ? `  color-scheme: ${options.colorScheme};\n` : '';
    return `${options.selector} {\n${scheme}${lines.join('\n')}\n}\n`;
  },
});

StyleDictionary.registerFormat({
  name: 'ds/ts-object',
  format: ({ dictionary, options }) => {
    const groups = new Map();
    for (const token of dictionary.allTokens) {
      const [group, ...rest] = token.path;
      const key = rest.length === 0 ? group : leafName(rest);
      const raw = token.$value ?? token.value;
      const value = token.$type === 'color' ? toRgba(raw) : token.$type === 'shadow' || token.$type === 'fontFamily' ? raw : toNumber(raw);
      const bucket = groups.get(rest.length === 0 ? '__root' : group) ?? new Map();
      bucket.set(key, value);
      groups.set(rest.length === 0 ? '__root' : group, bucket);
    }
    return JSON.stringify(Object.fromEntries([...groups].map(([g, m]) => [g, Object.fromEntries(m)])), null, 2);
  },
});

/** One dictionary per theme: SD resolves a single source set at a time. */
async function build(sources, platform) {
  const sd = new StyleDictionary({ source: sources, platforms: { out: platform }, log: { verbosity: 'silent' } });
  const [file] = await sd.formatPlatform('out');
  return file.output;
}

const CORE = ['source/core.tokens.json', 'source/layout.tokens.json'];
const cssPlatform = (selector, colorScheme) => ({
  // No value transforms on purpose: the authored values are already valid CSS, and the built-in
  // colour transform drops alpha from the modern `rgb(r g b / a)` syntax.
  transforms: [],
  files: [{ destination: 'x.css', format: 'ds/css-vars', options: { selector, colorScheme, showFileHeader: false } }],
});
const tsPlatform = { transforms: [], files: [{ destination: 'x.json', format: 'ds/ts-object', options: { showFileHeader: false } }] };

const [lightCss, darkCss, lightJson, darkJson, coreJson, nativeFontsJson] = await Promise.all([
  build([...CORE, 'source/theme.light.tokens.json'], cssPlatform(':root', 'light')),
  build(['source/theme.dark.tokens.json'], cssPlatform(":root[data-theme='dark']", 'dark')),
  build(['source/theme.light.tokens.json'], tsPlatform),
  build(['source/theme.dark.tokens.json'], tsPlatform),
  build(CORE, tsPlatform),
  // Native families are built apart from CORE on purpose: they must not reach tokens.css, where a
  // bundled family name is meaningless.
  build(['source/fonts.native.tokens.json'], tsPlatform),
]);

mkdirSync(OUT, { recursive: true });
writeFileSync(`${OUT}/tokens.css`, `${HEADER}${lightCss}\n${darkCss}`);

const light = JSON.parse(lightJson);
const dark = JSON.parse(darkJson);
const core = JSON.parse(coreJson);
const nativeFonts = JSON.parse(nativeFontsJson);
const palette = (t) => t.color;

writeFileSync(
  `${OUT}/index.ts`,
  `${HEADER}
/**
 * Semantic colours of one theme. Core keys serve any product; the finance keys are this product's
 * vocabulary. Values are widened to string on purpose: a theme is a set of keys, not of literals.
 */
export type Palette = Record<keyof typeof lightPalette, string>;

export const lightPalette = ${JSON.stringify(palette(light), null, 2)} as const;

export const darkPalette: Palette = ${JSON.stringify(palette(dark), null, 2)};

/**
 * CSS shadow recipes. Native must not use these raw: iOS takes shadowColor/Offset/Opacity/Radius
 * and Android takes elevation. Share the name, not the recipe.
 */
export const webShadows = ${JSON.stringify({ overlay: { light: light.shadow.overlay, dark: dark.shadow.overlay } }, null, 2)} as const;

/** Closed type scale (D-09). Numbers: points on native, pixels on the web. */
export const text = ${JSON.stringify(core.text, null, 2)} as const;

export const space = ${JSON.stringify(core.space, null, 2)} as const;

export const radius = ${JSON.stringify(core.radius, null, 2)} as const;

export const motion = ${JSON.stringify(core.motion, null, 2)} as const;

/** Minimum touch target, in points. */
export const tap = ${core.__root.tap};

/** Web chrome measurements. A native app sizes its own. */
export const layout = ${JSON.stringify({ sidebarWidth: core.sidebar.width, contentMax: core.content.max, bottomNavHeight: core['bottom-nav'].height }, null, 2)} as const;

/**
 * CSS font stacks, for the browser only. A device cannot use a fallback list: it needs the name of a
 * family bundled in the app, which is what \`nativeFonts\` carries.
 */
export const fontStacks = ${JSON.stringify(core.font, null, 2)} as const;

/**
 * Families of the fonts an app bundles, per platform: Android matches the asset file name and iOS
 * the PostScript name, so the map cannot be a single string. Weights are limited to the three UI and
 * two mono faces the type scale uses; anything else is added deliberately, not imported wholesale.
 */
export const nativeFonts = ${JSON.stringify(nativeFonts, null, 2)} as const;
`,
);

console.log(`tokens: ${Object.keys(palette(light)).length} per theme + ${Object.keys(core.text).length + Object.keys(core.space).length + Object.keys(core.radius).length} scale steps → ${OUT}`);
