import type { ReactNode } from 'react';

/**
 * Generated content, and the control that asks for it. Two rules are in the contract rather than in
 * the consumer: the action is quiet (never a primary button), and the panel has a state for a
 * provider that is not answering — so an unavailable model is something the screen renders, not an
 * error it throws.
 *
 * A third rule cannot live here and belongs to the application: when generation is switched off,
 * neither of these is rendered at all.
 */

export const AI_PANEL_STATES = ['ready', 'loading', 'unavailable'] as const;
export type AIPanelState = (typeof AI_PANEL_STATES)[number];

/**
 * The quiet control that starts a generation. It is a text control with a small ring, never filled
 * and never the section's primary button: nothing should be generated by someone aiming at Save.
 */
export type AIActionContract = {
  label: string;
  onPress: () => void;
  /** Blocks interaction and announces busy, like any other control in the system. */
  loading?: boolean;
  disabled?: boolean;
};

export type AIPanelContract = {
  state?: AIPanelState;
  /** Header label when the text is ready. */
  title?: string;
  /** The small mono figure on the right of the header: when it was generated. */
  meta?: string;
  /** What is happening, announced and shown beside the spinner while loading. */
  busyLabel?: string;
  /** The paragraph when ready; the plain sentence when unavailable. */
  children?: ReactNode;
};
