import { copyFileSync } from 'node:fs';
import { defineConfig } from 'tsup';

/** `src/` is generated by `scripts/build.mjs`; this only compiles it and carries the stylesheet over. */
export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm', 'cjs'],
  dts: true,
  clean: true,
  onSuccess: async () => {
    copyFileSync('src/tokens.css', 'dist/tokens.css');
  },
});
